### ISSUE TITLE
Music player UI broken at Galaxy Fold 3 resolution

### ISSUE THREAD

**Issue by CodeName393** [CTalvio/Kaleidochromic#12]
The music player UI is broken at Galaxy Fold 3 resolution as stated in the title.
So ,inside the player, all buttons are not recognized.
![Screenshot_20210830-155247_Jellyfin](https://user-images.githubusercontent.com/62503817/131298194-bd95407d-e646-477a-9f76-90bb55908915.png)

**Comment by CTalvio** [comment]
As stated in the readme, Kaleidochromic is no longer being worked on. But I doubt Ultrachromic will have fixed this particular issue, as it's not significantly different.

For reference, how does the UI behave without a theme?

**Comment by CodeName393** [comment]
I didn't know that this theme was discontinued and moved on to another theme.
The UI is broken even in the default theme...
Should I move this issue to a new theme first?

![Screenshot_20210830-185527_Jellyfin](https://user-images.githubusercontent.com/62503817/131322383-446e5cac-443f-4980-bd89-4d429f7559b3.png)

**Comment by CTalvio** [comment]
Well, considering the problem is present even when not using my themes, it's not exactly caused by my themes, is it?

You might want to figure out where you should open an issue, it's  either the JF android app github, or JF webUI github.

I could probably move the UI around to make it work, but that would make my theme a workaround for this issue, not a solution. Understand, my themes apply atop the default, the default theme is still doing the heavy lifting for how the UI should actually work. CSS override themes are just tweaks added on top.
